name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.pktrkt }}/chat-app .
        docker login -u ${{ secrets.pktrkt }} -p ${{ secrets.dckr_pat_R9kKZilu1KvmxGa5M0cM8W7wXmw }}
        docker push ${{ secrets.pktrkt }}/chat-app
      env:
        NODE_ENV: production
